# Development Composer

version: '3.7'

services:
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    ports:
      - '5000:5000'
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - MONGO_PORT=27017
      - MONGO_URL=api_mongo
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=mysecrettoken
    depends_on:
      - api_mongo


  api_mongo:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb

volumes:
  mongo_data: {}
  mongo_config: {}
